const EVEN_DIMENSIONS = 'scale=trunc(iw/2)*2:trunc(ih/2)*2';

// The only outputs /convert and /download's mp3 option can produce; ffmpeg never sees a user-chosen flag.
export const OUTPUT_FORMATS = {
  mp4: {
    kind: 'video',
    label: 'MP4 video',
    mime: 'video/mp4',
    args: [
      '-c:v',
      'libx264',
      '-preset',
      'veryfast',
      '-crf',
      '23',
      '-pix_fmt',
      'yuv420p',
      '-vf',
      EVEN_DIMENSIONS,
      '-c:a',
      'aac',
      '-b:a',
      '160k',
      '-movflags',
      '+faststart',
    ],
  },
  webm: {
    kind: 'video',
    label: 'WebM video',
    mime: 'video/webm',
    args: [
      '-c:v',
      'libvpx-vp9',
      '-crf',
      '33',
      '-b:v',
      '0',
      '-deadline',
      'realtime',
      '-cpu-used',
      '8',
      '-row-mt',
      '1',
      '-c:a',
      'libopus',
      '-b:a',
      '128k',
    ],
  },
  mp3: {
    kind: 'audio',
    label: 'MP3 audio',
    mime: 'audio/mpeg',
    args: ['-vn', '-c:a', 'libmp3lame', '-q:a', '2'],
  },
  m4a: {
    kind: 'audio',
    label: 'M4A audio',
    mime: 'audio/mp4',
    args: ['-vn', '-c:a', 'aac', '-b:a', '192k'],
  },
  ogg: {
    kind: 'audio',
    label: 'OGG audio',
    mime: 'audio/ogg',
    args: ['-vn', '-c:a', 'libopus', '-b:a', '128k'],
  },
  wav: { kind: 'audio', label: 'WAV audio', mime: 'audio/wav', args: ['-vn', '-c:a', 'pcm_s16le'] },
  flac: {
    kind: 'audio',
    label: 'FLAC audio (lossless)',
    mime: 'audio/flac',
    args: ['-vn', '-c:a', 'flac'],
  },
  png: { kind: 'image', label: 'PNG image', mime: 'image/png', args: ['-frames:v', '1'] },
  jpg: {
    kind: 'image',
    label: 'JPG image',
    mime: 'image/jpeg',
    args: ['-frames:v', '1', '-q:v', '2'],
  },
  webp: {
    kind: 'image',
    label: 'WebP image',
    mime: 'image/webp',
    args: ['-frames:v', '1', '-c:v', 'libwebp', '-quality', '90'],
  },
};
